#!/bin/bash
#=================================================================================
# Copyright (C) Andrzej Adamczyk (at https://blackdev.org/). All rights reserved.
#=================================================================================

clear

# default CPUs amount: 2
SMP="${1}"
if [ -z "${SMP}" ]; then SMP="2"; fi

# default Memory size: 64 MiB
MEM="${2}"
if [ -z "${MEM}" ]; then MEM="64"; fi

qemu-system-x86_64						\
	--enable-kvm						\
	-cpu max						\
	-smp ${SMP}						\
	-m ${MEM}						\
	-cdrom build/foton.iso					\
	-rtc base=localtime					\
	-audio driver=alsa,model=sb16,id=7			\
	-netdev user,id=virtio-net-0				\
	-device virtio-net-pci,netdev=virtio-net-0,mac=00:22:44:66:88:AA	\
	-object filter-dump,id=virtio-net-0,netdev=virtio-net-0,file=network.dump	\
	-serial stdio						\
#	-readconfig tools/qemu-ehci-uhci.cfg			\
#	-device usb-kbd,bus=ehci.0				\
#	-device usb-mouse,bus=ehci.0				\
#	-device qemu-xhci					\
#	-device usb-kbd						\
#	-device usb-mouse					\
