#!/bin/bash
#=================================================================================
# Copyright (C) Andrzej Adamczyk (at https://blackdev.org/). All rights reserved.
#=================================================================================

readelf --symbols -W ${1} | grep DEFAULT | sort -k 2
